# Generated by Django 5.2.1 on 2025-05-21 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgImages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimages',
            name='image_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
