# Generated by Django 5.2.1 on 2025-05-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonials_text', models.CharField(max_length=200)),
                ('testimonials_name', models.CharField(max_length=200)),
                ('testimonials_job', models.CharField(max_length=200)),
                ('testimonials_date', models.DateTimeField(verbose_name='date published')),
                ('stars', models.IntegerField(default=5)),
            ],
        ),
    ]
