# Generated by Django 5.2.1 on 2025-05-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials_images/'),
        ),
    ]
